# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=2.0.7
maven_group=fbanna.chestprotection
archives_base_name=chestprotection


# Dependencies
fabric_api_version=0.161.0+26.3
loom_version=1.18-SNAPSHOT
sgui_version=2.2.1+26.3